### PR TITLE
Add Android contact images.

### PR DESCRIPTION
**Pull request by kanerogers**
Hey, there!

I've added contact images for Android. I've tested this pretty thoroughly with my application, seems to work fine.

Let me know if there's anything you need me to do!

### CODE REVIEW

**Comment by morenoh149** [comment]
can you instead let this conform to the ios API? https://github.com/rt2zz/react-native-contacts#displaying-thumbnails-ios-only meaning if a photo is available return it in the `thumbnailPath` field

**Comment by kanerogers** [comment]
Hi there @morenoh149! Sorry for the long delay before replying.

I'm not 100% sure what you mean. When converting the `Contact` to a map, we do:

```
contact.putString("thumbnailPath", photoUri == null ? "" : photoUri);
```

Which takes `Contact.photoUri` and places it into the `thumbnailPath` field. I've got the same JavaScript code talking to both the iOS and Android API successfully. 😄 

Let me know if I'm missing something!

**Comment by morenoh149** [comment]
ah I see at https://github.com/kanerogers/react-native-contacts/blob/15ff1686e0437bf3e72fb92c9d5dbaf50c7daef4/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L140 thanks

**Comment by kanerogers** [comment]
Haha, no worries. Should have replied earlier, just forgot about it.

I've got some more Android stuff coming..

K

**Pull request merged**
