### PR TITLE
Added support to return the 'me' profile along with the other contacts

### PR DESCRIPTION
**Pull request by npomfret**
Added support to return the 'me' profile along with the other contacts

### CODE REVIEW

**Comment by morenoh149** [comment]
what happens if a user omits the READ_PROFILE permission?

**Comment by npomfret** [comment]
Good question.  I guess it won't work, but that's the same problem as if they don't accept the other permissions isn't it?  Or or there some guards in place?

**Comment by morenoh149** [comment]
It'd be great if it could return all contacts minus ME if the permission is not included.

**Comment by npomfret** [comment]
I don't thin it's possible to switch off a permission in Android is it?  I think you either accept permissions when you down load the app, or you don't get to down load it.

**Comment by morenoh149** [comment]
true. I was thinking from the developer point of view. If I want to use `react-native-contacts` and only get contacts (not create contacts) the module works with just the `android.permission.READ_CONTACTS` permission. Will the code crash if a developer omits `android.permission.READ_PROFILE` and runs `getAll()`?

**Comment by npomfret** [comment]
You mean if you manually change the manifest for what ever reason?

**Comment by morenoh149** [comment]
yeah as a developer wanting to use the least number of permissions. Too niche?

**Comment by npomfret** [comment]
I think so, if you're going to edit the source feel free to do what ever you need.  I wouldn't let this prevent pushing to master.

**Pull request merged**
