### PR TITLE
Update android gradle config

### LINKED ISSUE #247: Changes needed for gradle 3.0.1 compatibility
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

### PR DESCRIPTION
**Pull request by morenoh149**
* fixes #247

### CODE REVIEW

**Comment by morenoh149** [comment]
@pacamara please review

**Comment by giacomocerquone** [comment]
Applied this fix and didn't work. Any hints?
I'm using gradle 4.4 and 3.1 plugin

**Comment by abhaynpai** [comment]
Any updates on this patch? We are getting an error while syncing the project.

**Comment by morenoh149** [comment]
@abhaynpai the PR is now outdated. No updates on my end. Fixes appreciated!

**Pull request closed without merging**
