### PR TITLE
Allow fomattedAddress in openContactForm android

### LINKED ISSUE #454: openContactForm function not support the formattedAddress in Android
I am using the latest version of react-native-contacts and as I said in the title the formattedAddress is not support in the openContactForm function.
Also, I checked the module and that is missing.
Please update the code asap.
Thank you

### PR DESCRIPTION
**Pull request by MebDevelop**
fixes #454

### CODE REVIEW

**Comment by MebDevelop** [comment]
Please check this and merge this.
I am copying the Java file every time after npm install.
It's very stressful.
Please merge this.
Thank you!

**Comment by morenoh149** [comment]
how does this compare to the iOS version? does iOS return the address?

btw, you can use `npm link` to change your dependencies locally.

**Comment by MebDevelop** [comment]
You asked about the iOS, and I think in iOS version the formattedAddress is not needed.
Because in android phone there is only address field for showing contact. So we use formattedAdress in android.
And the ios, there are street, city, state, postalcode, country... so we don't need formattedAddress.

**Comment by morenoh149** [comment]
is this new field used in the example app? https://github.com/rt2zz/react-native-contacts/tree/master/example if not please add that as well.

**Comment by MebDevelop** [comment]
I think there is no example of openContactForm in that example.
So I think it doesn't need to update example.

**Comment by morenoh149** [comment]
hmm, we should add an example of the openContactForm

**Comment by MebDevelop** [comment]
I will pr if I have time.

**Pull request merged**
