### PR TITLE
Additional contact details

### PR DESCRIPTION
**Pull request by Proberts**
[Readme.md](https://github.com/Proberts/react-native-contacts/) has a table showing the contact fields that have been added. The Android implementation is complete. iOS implementation will come next. (Not sure when to submit pull req. I'm new to GitHub and feedback is appreciated.)

Fields added:

- nickname
- phonetic(family|middle|given)Name
- websites
- postalAddresses
- note
- birthday
- thumbnailPath for addConact()/updateContact()

In addition to new fields:

Refactored addContact() and updateContact(), optimized array fields with hashmap
Fixed bug in getContacts() causing thumbnail to be copied multiple times per contact

### CODE REVIEW

**Comment by morenoh149** [comment]
If we could get the same features for both platforms that would be best.

Also please squash your commits down and summarize the changes from top to bottom. http://chris.beams.io/posts/git-commit/

**Comment by Proberts** [comment]
OK. I'll re-submit when I have the iOS port working.

Thanks for the link. (I tired to squash but gave up after 4 hours and a messed up branch...increasing expletives in my google query didn't return more helpful results. I'll try again.)

**Comment by npomfret** [comment]
I think the commits can be squashed by the merger so maybe don't worry about it

**Comment by npomfret** [comment]
Some of the work you've done has been addressed by another change I've just merged.  Sorry for the conflict.

**Comment by Proberts** [comment]
The iOS version is now up to date with the Android version and documentation has been updated.

I'm unsure what to do next. When I click on the "resolve conflicts" button above I get a perpetual spinning activity indicator. Sorry to newb all over this attempt to contribute. I'm adding groups support next and will try to do it better.

FWIW - I'm inclined to suggest that our version is accepted in place of the conflicting version. The already committed version that adds address does it in a way that is not supported the same on both iOS and Android.

**Comment by morenoh149** [comment]
you need to resolve the conflicts, i.e., make your solution the one that should be kept. And then squash commits. I'll squash it for you in another branch to demonstrate.

**Comment by Proberts** [comment]
@morenoh149 Are you able to get _Resolve conflicts_ to work? When I click on it I get a UI with the files listed on the left, but a spinning activity indicator in the main window that never stops. (tried in  Chrome[55/Win,OS X 54/Linux], FF[50/linux], IE11, Safari 10)

**Comment by morenoh149** [comment]
I see this when I click on it 
screen shot 2016-12-20 at 1 09 35 pm

perhaps you should try a different machine

*running mac osx Chrome 55*

**Comment by npomfret** [comment]
You might need to resolve conflicts in an IDE, but you can just accept yours and overwrite the committed code if you're sure yours is an improvement.

Things to keep though are:

 * android - no longer do image copying, we now just use the _native_ uri instead of the file uri
 * iOS - the code that copies the image was simplified recently, lets keep the simplified version.

If you get totally stuck with the merge maybe one of us could take ownership of the PR

**Comment by Proberts** [comment]
Would this be a reasonable course of action for me:

Create temp github account so I can create a second fork
Copy in my files
Manually merge changes committed to this repo after I originally forked it
Submit pull request for the second fork

**Comment by Proberts** [comment]
@morenoh149 Maybe it's a permissions issue. The three OSes I tried were all different machines. Chrome 55 on OS X didn't work for me.

**Comment by morenoh149** [comment]
I'd assume if github didn't want to give you permission the button would be disabled altogether. It's your PR I'm pretty sure you can resolve the conflicts on it.

**Comment by npomfret** [comment]
Resolving conflicts isn't something I'd do on the web.  I'd use a decent IDE to do it, something that understands git and java (in this case).  Otherwise you're likely to get compile errors, android studio should do the job nicely I think.  You need to pull in the changes from master into your fork, resolve them, push them, and then we can merge the fork.  Follow this https://help.github.com/articles/syncing-a-fork/ to get the changes (assuming you already done this bit https://help.github.com/articles/configuring-a-remote-for-a-fork/ to add the upstream repo).

In android studio, assuming you've got git set up in the version control settings, go to the version control tab.  The conflicting files will be in red, right click each one and choose _resolve text conflict_.  It'll pop up a three way view: your changes, the changes in master and the merged result in the middle. 

Hope that helps.

Alternatively, if you know your changes well you could discard them completely and re-do them on a fresh copy of master?

**Comment by Proberts** [comment]
@morenoh149 @npomfret Thanks for the continued help. I've submitted a new pull request.

**Pull request closed without merging**
