### PR TITLE
Android company support

### LINKED ISSUE #74: Support Company and Job Title fields [Android]
We need an Android pull request to match https://github.com/rt2zz/react-native-contacts/pull/73

### PR DESCRIPTION
**Pull request by dbhowell**
Added Android support for company and jobTitle
(fixes #74, refs #73)

### CODE REVIEW

**Comment by morenoh149** [comment]
wow thanks

**Comment by dbhowell** [comment]
Glad I could contribute back. What timeframe is a new npm publish?

**Comment by morenoh149** [comment]
tonight

**Comment by morenoh149** [comment]
new version published. Thanks for your patience. https://www.npmjs.com/package/react-native-contacts

**Pull request merged**
