### PR TITLE
Example app

### PR DESCRIPTION
**Pull request by mikehardy**
Hi there!

I was about to integrate this module into a project and noticed there wasn't an example when I went to test it

Possibly related to #382 - I've implemented an example - or more than an example (because it's hard to keep them updated) - I've implemented a "refresh-example" script that will take a fresh template app from `react-native init`, then apply the minimum amount of changes required to make it show contacts and document how to use it

I used the same style in [react-native-community/react-native-device-info](https://github.com/react-native-community/react-native-device-info) and it seems to work well for me there, maybe it's useful here?

I tested it on Android API28 (real device), API18 (emulator - API16 and API17 emulators are iffy unfortunately - but I'm an Android person and I don't there there's a reason it wouldn't work on them as well...). I also tested on "iPhone 5s (9.3)" and "iPhone 7 (12.1)" and "iPhone X (11.2)" simulators and everything seemed fine.

The 1st and 4th commits are where there are real "changes" - the 1st adds a dev dependency to the main project, and the fourth implements the react-native-contacts specific part of the example. The 2nd and 3rd are just a clean template, then the npm install and link, so they are pretty huge but also just automatic boilerplate.

Cheers

### CODE REVIEW

**Comment by morenoh149** [comment]
Thanks a lot for this! Is this example in the same spirit as examples in other rn projects like https://github.com/react-native-community/react-native-video/tree/master/examples ?

Historically I've maintained an example as a separate project at https://github.com/morenoh149/react-native-contacts-test but I think it is more common in rn land to have an example project right inside the codebase. So I'm open to this.

Please review https://github.com/morenoh149/react-native-contacts-test and see if you can borrow any more ideas from there. I'd be happy to merge this PR when you get back to me.

**Comment by mikehardy** [comment]
Oh, I did not realize there was already an example :-), sorry. I am not aware of a convention in rn-land for example other than in-tree except for very large projects (like react-native-firebase where they provide a fully separate project that you can then begin work with). I am aware that a single page app is somewhat nice if you incorporate tests later as it is easier to drive the UI or just scrape results indicating it is working when doing e2e tests. I will not have time to re-look at this for a while, but feel free to just take the "scripted refresh" style (that is, the actual shell script - it is the only special part) and bin the rest if you don't like it. As a maintainer on other projects I find that automating the construction of the example is useful as otherwise keeping up with react-native template changes becomes a fresh burden

**Comment by mikehardy** [comment]
(for completeness, when I look at your example, I will specifically be looking for exercise of the other APIs - create update delete etc) with a view towards incorporating in an App.js that is as simple as possible, still within an automatically constructed framework)

**Comment by morenoh149** [comment]
I think in repo example is more common in rn-land. Better than what we have.

**Comment by mikehardy** [comment]
I didn't get a chance to look at the App.js you had so you very likely had extra functionality in there - but - easy to copy-paste over :-). Either way I just hope this helps, I'm using your library in my project and I appreciate the work

**Pull request merged**
