### PR TITLE
Issue 305 fix - Added 'React/Core' dependency to podspec file.

### PR DESCRIPTION
**Pull request by jcekstrom**
Adding React/Core dependency to the podspec.

### CODE REVIEW

**Comment by morenoh149** [comment]
closed in favor of #230

**Comment by achintyaha** [comment]
Does adding s.dependency 'React' will also solve this issue?

**Comment by morenoh149** [comment]
it's already there https://github.com/rt2zz/react-native-contacts/blob/master/react-native-contacts.podspec#L16

**Comment by achintyaha** [comment]
But I am still getting this issue.

tacts.h:1:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by Kendysond** [comment]
hi @achintyaha , were you able to find a solution?

**Comment by achintyaha** [comment]
@Kendysond I just removed all the files and linking and again did the whole linking process and it worked.

**Pull request closed without merging**
