### PR TITLE
Replacing NSLog with RCTLog

### PR DESCRIPTION
**Pull request by gauravmnit07**
NSLog print the logs in release mode as well. Its better to use RCTLog as that will be printed only in debug builds and governed by RCTLOG_ENABLED

### CODE REVIEW

**Comment by morenoh149** [comment]
good idea 👍

**Comment by morenoh149** [comment]
@gauravmnit07 is there an android equivalent for RCTlog?

**Comment by Pradeet** [comment]
To prevent logs in release build for android... we can use Log.d()

**Comment by morenoh149** [comment]
looks good. Will open issue for android version.

**Pull request merged**
