### PR TITLE
fix cursor check to null

### PR DESCRIPTION
**Pull request by nucleartux**
fixes https://github.com/rt2zz/react-native-contacts/issues/10

### CODE REVIEW

**Comment by rt2zz** [comment]
:+1: thank you!

**Comment by niftylettuce** [comment]
Can we cut another release for this?  I'm testing it out today.

**Comment by niftylettuce** [comment]
@nucleartux @rt2zz still getting errors, here's a screenshot...

screenshot_2015-11-21-21-27-50

I'm calling `getAll` and this happens - I think you need to do some other stuff than just this null fix to get it to work properly.  Maybe take a look at how PhoneGap/Cordova wrote their plugin?  I will gladly pay if you get this working @nucleartux

**Comment by nucleartux** [comment]
Something wrong with your code(reactNativeContacts2?). Can you copy paste it here ?

**Comment by niftylettuce** [comment]
I did npm install --save rt2zz/react-native-contacts, so the code is the
same as master branch here on GitHub.

**Comment by nucleartux** [comment]
Please try 
direct call NativeModules.Contacts.getAll

**Comment by niftylettuce** [comment]
I get a lot of this console output:

screen shot 2015-11-22 at 2 09 28 am

**Comment by rt2zz** [comment]
I do not have an answer at the moment, but from a bigger picture the current code (which I wrote) is woefully slow, and at the very least would need to be pushed to a background thread before it could be considered usable.

I do not have a timetable for fixing this as of now, but am open to suggestions / PRs.

@niftylettuce if you are interested in paying I can probably get you in touch with someone who can hammer this out.

**Comment by niftylettuce** [comment]
please do put me in touch, its way too slow.  niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
@nucleartux it runs, but it's super slow, and some of the contacts come back blank -- like the nulls are never cleaned up or something?  It's just super slow in general - how can we make this fast? /cc @rt2zz

**Pull request merged**
