### PR TITLE
Fixes #234: Android compilation error regarding abstract method createJSMod…

### LINKED ISSUE #234: Android compile error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage
Since most recent RN-versions (0.50 here) the following compilation error occurs with android:

> ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage

```
./node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java:13: error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeContacts implements ReactPackage {
       ^
1 error
```

### PR DESCRIPTION
**Pull request by itinance**
…ules

### CODE REVIEW

**Comment by morenoh149** [comment]
similar solution in https://github.com/facebook/react-native-fbsdk/pull/354 basically allows newer version of RN to use the module without error. Seems to be a new required api method for native modules.

**Comment by morenoh149** [comment]
I'm going to have to revert this change. See https://github.com/AndrewJack/react-native-fbsdk/blob/master/android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java they also ended up later removing the override.

**Comment by morenoh149** [comment]
conversation at https://github.com/facebook/react-native-fbsdk/pull/345 looks like we should keep the method but remove the `@Override` syntax? @itinance could you advise?

**Comment by itinance** [comment]
Yes, @morenoh149. I also investigated a bit in the meanwhile and wanted to turn back to you. Removing @override would be the best option! Sorry!

**Comment by morenoh149** [comment]
discussion at https://github.com/rt2zz/react-native-contacts/issues/236

**Pull request merged**
