### PR TITLE
Adding "findContactByNumber" api

### PR DESCRIPTION
**Pull request by Louies89**
Hi,
I saw there is an API "findContactByNumber" present in react-native-simple-contacts, its very useful for look-up the contact number. So for trial purpose I copied the functionality from react-native-simple-contacts to react-native-contacts "ContactsManager.java" and it runs very well.

So below is the modification I have done in "ContactsManager.java" file:

```java
    import android.net.Uri;
    import com.facebook.react.bridge.Promise;
    import org.json.JSONArray;
    import org.json.JSONException;
    import org.json.JSONObject;

    @ReactMethod
    public void findContactByNumber(String number, Promise promise) {
		Context context = getReactApplicationContext();
        ContentResolver cr = context.getContentResolver();
        Uri uri = Uri.withAppendedPath(
                ContactsContract.PhoneLookup.CONTENT_FILTER_URI,
                Uri.encode(number)
        );

        JSONObject json = new JSONObject();

        Cursor cursor = cr.query(
                uri,
                new String[]{
                        ContactsContract.PhoneLookup.DISPLAY_NAME,
                        ContactsContract.PhoneLookup.PHOTO_THUMBNAIL_URI
                },
                null, null, null
        );
        if (cursor.moveToFirst()) {
            try {
                json.put(
                        "display",
                        cursor.getString(
                                cursor.getColumnIndex(ContactsContract.PhoneLookup.DISPLAY_NAME)
                        )
                );
                json.put(
                        "avatar",
                        cursor.getString(
                                cursor.getColumnIndex(
                                        ContactsContract.PhoneLookup.PHOTO_THUMBNAIL_URI
                                )
                        )
                );
            } catch (JSONException exc) {
                //Log.e('Contact_Err', exc.toString());
            }

        } else {
            //Log.d('Contact_Debug', "Contact: Not found.");
        }
        cursor.close();
        promise.resolve(json.toString());
    }
```
Request to add this API for betterment of the package.

I have no experience in Java coding, so if I have done any mistake or idiotic thing, please forgive me.

Thank You.

### CODE REVIEW

**Comment by morenoh149** [comment]
@Louies89 something odd with this PR. You should only have to submit one commit onto master.

**Comment by Louies89** [comment]
@morenoh149 I tried same, but I was unable to do it. So I put it here. Can you please guide me or let me know the link.

**Comment by morenoh149** [comment]
at the top of this PR it says `	Louies89  wants to merge 186 commits into morenoh149-patch-1 from master`. That's wrong you should be trying to merge from a branch on a fork you own into this repo's `master`.

**Comment by Louies89** [comment]
@morenoh149  Sorry for the late response. I do not own a fork of the repo.

Please take it as a suggestion and use the code. As I do not have experience in Java I do not want to do any changes which shall affect many people. 

Please let me know, if I will delete the PR, it will solve the problem.

**Comment by morenoh149** [comment]
@Louies89 you should make a fork. It's the button in the upper right hand corner.

**Comment by Louies89** [comment]
@morenoh149 
Really I do not understand how to do this PR. And I am unable to give time to understand this process. By doing a quick reading, what I understand is, Pull Request is some thing like, I have to do some changes in the code and commit to a branch. 

But as I do not have any prior experience and lacking time to learn it now. I request you, Please you take it forward as if you are the PR Owner and do needful changes. 

If I do something, and it will create a problem, lot of folks using this package shall be affected.

So please take care of this, I am closing this. 

Please do not mind. :)

**Comment by morenoh149** [comment]
@morenoh149 identify diff from master and submit pr against it.

**Comment by rahsheen** [comment]
Does anyone know why this isn't merged since March? Is something wrong with it? (besides the currently existing conflicts, that is :) )

**Comment by morenoh149** [comment]
@rahsheen the conflicts. To fix I would open a new branch off master and copy paste the proposed changes and test that they work. Feel free to do this.

**Comment by hatemalimam** [comment]
should be closed, already resolved by https://github.com/rt2zz/react-native-contacts/pull/416

**Pull request closed without merging**
