### PR TITLE
Add more contact details, set thumnail image

### PR DESCRIPTION
**Pull request by Proberts**
Readme.md has a table showing the contact fields that have been added. The Android implementation is complete. iOS implementation will come next. (Not sure when to submit pull req. I'm new to GitHub and feedback is appreciated.)

Fields added:

- nickname
- phonetic(family|middle|given)Name
- websites
- postalAddresses
- note
- birthday
- thumbnailPath for addConact()/updateContact()

In addition to new fields:

Refactored addContact() and updateContact(), optimized array fields with hashmap

### CODE REVIEW

**Comment by npomfret** [comment]
Hi @Proberts - there's lots of activity on this project, everyone is getting merge conflicts.  Could you address yours before we look at it?

We prefer to add iOS and Android functionality at the same time.  If you could attempt the iOS stuff that would be ideal.  However, if you can't maybe we could merge this on its own. @morenoh149 may have a stronger opinion.

**Comment by Proberts** [comment]
@npomfret The iOS work is complete. Both platforms are at parity, including delete.

**Comment by npomfret** [comment]
ok, great.  The readme is still in conflict though, can you resolve?

**Comment by Proberts** [comment]
@npomfret I saw there were some additional conflicts when I fetched and merged, some being in the iOS tree. I don't have a way to test iOS at the moment, only Android (I'm on vacation and don't have access to my Mac. I'm back in my office Jan 2.) Kdiff3 auto-merged them. I'm not sure how confident to be about kdiff3's choices - it's a new tool for me.

**Comment by npomfret** [comment]
Ok, let's look at this when you get back.

**Comment by npomfret** [comment]
Hi - sorry but the iOS implementation has changed to use a new API.  And some of your changes are already in there (job title, company, postal addresses and updating the thumbnail).  If you get a chance to update your iOS implementation I'd like to take another look at this.

Also, there's a test suite that you can use to check your changes are working: https://github.com/morenoh149/react-native-contacts-test

Did you implement update and add for the new fields as well as get?

**Comment by Proberts** [comment]
Get, add, and update all support the new fields. Delete on Android is also implemented.  (FWIW my master is ahead of this branch.)

I see the test app has been updated. I'll take another look at it.

The delivery date for the app I'm working on is coming up so it might take me a while to get to it. The refactoring I did to the Android code makes it time consuming to merge changes to this repo. Git merges and flags conflicts in unrelated sections of code.

**Comment by AndrewMigal** [comment]
Hi. Guys, could you please give any predictions when will you be able to merge this?

**Comment by npomfret** [comment]
It has conflicts that need resolving first.  Also, we have a basic test suite now here https://github.com/morenoh149/react-native-contacts-test which should be added to.

**Comment by morenoh149** [comment]
Closing this as abandoned by author. Please ping to reopen or simply rebase it and resubmit. I'll add a CONTRIBUTING.md file so this doesn't happen again.

**Comment by Proberts** [comment]
I haven't abandoned the fork. I just don't have the resources atm to update for conflicts in the current head given the iOS API change. My API has diverged significantly so a merge may not be desirable to existing users anyway.

**Comment by fgarcilazo** [comment]
@morenoh149 linking you to the mentioned PR.

**Comment by morenoh149** [comment]
@fgarcilazo i see. Could you please resubmit this as a fresh PR integrating as is is not possible.

**Pull request closed without merging**
