### PR TITLE
Feature/delete android contacts

### PR DESCRIPTION
**Pull request by newseedit**
Added deleteContact to android as well, will remove data from data table, raw contacts table, and contacts table based on recordid.

### CODE REVIEW

**Comment by kevinjom** [comment]
no test?

**Comment by newseedit** [comment]
Is it possible to add this to the test repository? I have only made changes to ContactsManager.java, which I don't think is included in the test repository. Also there's already a test for deletion of contacts, so I don't know if there's anything I can add to the test itself. Please inform me if I'm incorrect, and I will try to add a test to the test repository.

**Comment by morenoh149** [comment]
I'm actually deprecating the test repo in favor of an example app in the project itself. The only thing stopping merging of this PR is another person confirming that it works. Until I get time to test it out myself. Thanks for the PR.

**Comment by ganes1410** [comment]
It works

**Comment by morenoh149** [comment]
delete contacts was added in https://github.com/rt2zz/react-native-contacts/pull/190 thanks for the PR and tests!

**Pull request closed without merging**
