### PR TITLE
added "note" property

### PR DESCRIPTION
**Pull request by anton-aleksandrov**

### CODE REVIEW

**Comment by anton-aleksandrov** [comment]
https://github.com/rt2zz/react-native-contacts/issues/189

**Comment by cristianosantos95** [comment]
Any updates on this PR? It's a great feature 😁

**Comment by anton-aleksandrov** [comment]
@cristianosantos95 no updates. I've created it, owner ignored it. Just check the changed, you can replicate it on your own.

**Comment by cristianosantos95** [comment]
will do that, thanks @anton-aleksandrov !

**Comment by morenoh149** [comment]
There are some conflict that need to be resolved. I can get to it after I fix the gradle building on modern versions of RN.

**Comment by morenoh149** [comment]
closing in favor of https://github.com/ConsenSys/Linnia-Smart-Contracts/issues/92 thanks for the PR

**Pull request closed without merging**
