### PR TITLE
Request for READ_CONTACTS permission on android

### LINKED ISSUE #180: Does not request permission on android when calling requestPermission
When using `requestPermission` ReactMethod on android `ContactsManager` react module, it only checks if permission for `READ_CONTACTS` is granted. It needs to prompt user for permission for API 23+

```java
@ReactMethod
public void requestPermission(Callback callback) {
    callback.invoke(null, isPermissionGranted());
}
```
[Line Reference](https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L313)

### PR DESCRIPTION
**Pull request by jebora**
## Why
We needed to request and prompt users for reading contacts for API23+ since it is not automatically granted.

## Changes
- For ReactMethod `requestPermission`, if permission not granted call `ActivityCompat.requestPermissions( ... )` and statically keep a reference of callback for feedback when handling `onRequestPermissionsResult`
- Add static methods for `onRequestPermissionsResult` in `ReactNativeContacts.java` and `ContactsManager.java`

## Issue
Fixes #180

### CODE REVIEW

**Comment by FrancisToth** [comment]
Any plan to merge this in master ?

**Comment by morenoh149** [comment]
@FrancisToth have you reviewed it and confirm it works?

**Comment by FrancisToth** [comment]
Well, having some tests would be awesome :) Maybe then we could review this properly.

**Comment by morenoh149** [comment]
reading https://github.com/rt2zz/react-native-contacts/blob/master/CONTRIBUTING.md shows the test should be added to https://github.com/morenoh149/react-native-contacts-test @jebora needs tests

**Comment by jebora** [comment]
@morenoh149 So I tried making a test for this the other day, but it seems like it's always automatically granting it contacts permissions, even on API 23+. In our app, we're integrating RN in our existing native code base and created our own ReactFragment/Activity that uses a react view factory with a common ReactInstanceManager. Is using FB's ReactActivity automatically grants required permissions? This shouldn't be the case right?

**Comment by morenoh149** [comment]
I believe the test app still uses android 22 https://github.com/morenoh149/react-native-contacts-test/blob/master/android/app/src/main/AndroidManifest.xml#L11 please update it

**Comment by antoinerousseau** [comment]
requestPermission not working on recent Android versions is quite a major issue since it mease it simply does not work. any clue why this PR never made it?

**Comment by morenoh149** [comment]
@antoinerousseau it got held up by the testing requirement. Does this PR work for you?

**Comment by antoinerousseau** [comment]
@morenoh149 haven't tried it, I'm just manually requesting permissions but it should be handled by this package

**Comment by jebora** [comment]
Hi all, sorry I completely forgot about this Pr. I'll make time to write a test later today

**Comment by jebora** [comment]
Hello. Made an integration test here https://github.com/morenoh149/react-native-contacts-test/pull/6

Finally, sorry for delay 😅

**Comment by morenoh149** [comment]
no worries. This is all volunteer time.

**Pull request merged**
