### PR TITLE
Fix Compilation Error in React Native 0.47.0

### PR DESCRIPTION
**Pull request by pohodnya**

### CODE REVIEW

**Comment by morenoh149** [comment]
@pohodnya thank you. Does this fix an outstanding issue?

**Comment by pohodnya** [comment]
@morenoh149 
createJSModules was removed in React Native 0.47.0 and results in the attached Build Error.
removing `@Override` fixes build (didn't remove function because I don't know if it should be kept for downard compatability?)

**Comment by Alex-Mann** [comment]
When is the next npm release planned? I am experiencing this issue with `v0.8.0` but can confirm it has been fixed after pulling master.

**Comment by morenoh149** [comment]
@Alex-Mann version 0.9.0 has been published on npm for a while now. Just updated the github project now. Let me know if it works.

**Pull request merged**
