### PR TITLE
fix middlename/lastname being null

### PR DESCRIPTION
**Pull request by anisjonischkeit**

### CODE REVIEW

**Comment by morenoh149** [comment]
What issue does this fix? why is returning null not good?

**Comment by anisjonischkeit** [comment]
What does it fix?
Sometimes a middlename/familyname is null, sometimes it is an empty string. When it is one or the other is pretty random (simply clicking on the middlename field seems to set it to empty string).

Why is returning null not good:
A: The index.d.ts file says it won't return null (so I assume someone didn't think it could null).
B: It doesn't really make any sense as per the comment above
> Sometimes a middlename/familyname is null, sometimes it is an empty string. When it is one or the other is pretty random (simply clicking on the middlename field seems to set it to empty string).
C: It's also pretty annoying to have to null check and empty string check to see if there is a value as well as having to null check if you want to concat a fullname

As far as the public API of this library goes, making the types match what actually happens (a null being returned) rather than fixing the implementation would also be a breaking change.

**Comment by morenoh149** [comment]
So this PR helps conform better to the typescript definitions? that is a good thing.

**Comment by anisjonischkeit** [comment]
correct. I came across it while using the typescript bindings and was wandering why nulls were being displayed but I wasn't getting type errors

**Pull request merged**
